server:
  port: 14713

spring:
  mail:
    host: smtp.qq.com
    username: ipziunvw420850@qq.com
    password: xxx
    properties:
      mail.smtp.ssl.enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mystudyplant
    username: postgres
    password: xxx
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    uris: http://localhost:9200
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: xxx
      database: 0
      timeout: 5000ms
  servlet:
    multipart:
      max-file-size: 10MB       # 閸楁洑閲滈弬鍥︽閺堚偓婢堆冦亣鐏?      max-request-size: 50MB    # 閺佺繝閲滅拠閿嬬湴閻ㄥ嫭娓舵径褍銇囩亸蹇ョ礉閺€顖涘瘮婢舵碍鏋冩禒鏈电瑐娴肩姵妞傞幀璇层亣鐏忓繘妾洪崚?
sa-token:
  token-name: studytoken
  timeout: 25920000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  is-read-cookie: true
  is-read-header: true
  debug: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: MyStudyPlant
  endpoint:
    health:
      show-details: always

minio:
  endpoint: http://127.0.0.1:9000
  access-key: tkdawenhao
  secret-key: xxx
  bucket-name: studyplant-data
  secure: false
  region: us-east-1

logging:
  level:
    # 瀵偓閸?ES 鎼存洖鐪扮拠閿嬬湴鏉╁€熼嚋
    tracer: TRACE

ai:
  siliconflow:
    api-key: xxx

crawler:
  # 閸嬪洨缍夐弬鍥у絺鐢啰娈戞担婊嗏偓鍖閿涘矂娓剁憰浣规Ц閺佺増宓佹惔?user 鐞涖劑鍣烽惇鐔风杽鐎涙ê婀惃?ID
  author-id: 7

github:
  token: "xxx" # 鐠囧嘲婀潻娆撳櫡婵夘偄鍙嗘担鐘垫暤鐠囬娈?GitHub Classic Token (娴犫偓娑斿牊娼堥梽鎰板厴娑撳秶鏁ら柅?


